#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE_PATH="${ENV_FILE:-.env.dev}"
LANGGRAPH_BIN="${LANGGRAPH_BIN:-$ROOT_DIR/.venv/bin/langgraph}"
LANGGRAPH_CONFIG="${LANGGRAPH_CONFIG:-$ROOT_DIR/langgraph.json}"
RUNTIME_ENV_FILE="$ROOT_DIR/.env.langgraph.runtime.local"
RUNTIME_CONFIG_FILE="$ROOT_DIR/.langgraph.local.json"
RUNTIME_ENV_REF="./$(basename "$RUNTIME_ENV_FILE")"
source "$ROOT_DIR/scripts/env.sh"

BASE_ENV_FILE="$(resolve_env_file "$ROOT_DIR" "$ENV_FILE_PATH")"
LOCAL_ENV_FILE="$(env_local_file "$BASE_ENV_FILE")"

append_env_file() {
  local env_file="$1"

  while IFS= read -r line || [[ -n "$line" ]]; do
    printf '%s\n' "$line"
  done < "$env_file"
}

if [[ ! -x "$LANGGRAPH_BIN" ]]; then
  echo "langgraph nao encontrado em $LANGGRAPH_BIN. Rode make install primeiro." >&2
  exit 1
fi

if [[ ! -f "$BASE_ENV_FILE" ]]; then
  echo "Arquivo de ambiente nao encontrado: $BASE_ENV_FILE" >&2
  exit 1
fi

{
  echo "# Generated by scripts/run_langgraph_dev.sh. Do not commit."
  echo "# Base: $BASE_ENV_FILE"
  append_env_file "$BASE_ENV_FILE"
  if [[ -f "$LOCAL_ENV_FILE" ]]; then
    echo
    echo "# Local overrides: $LOCAL_ENV_FILE"
    append_env_file "$LOCAL_ENV_FILE"
  fi
} > "$RUNTIME_ENV_FILE"
chmod 600 "$RUNTIME_ENV_FILE"

python3 - "$LANGGRAPH_CONFIG" "$RUNTIME_CONFIG_FILE" "$RUNTIME_ENV_REF" <<'PY'
import json
import sys
from pathlib import Path

config_path = Path(sys.argv[1])
runtime_config_path = Path(sys.argv[2])
runtime_env_ref = sys.argv[3]

config = json.loads(config_path.read_text(encoding="utf-8"))
config["env"] = runtime_env_ref
runtime_config_path.write_text(
    json.dumps(config, indent=2, ensure_ascii=False) + "\n",
    encoding="utf-8",
)
PY

echo "LangGraph dev usando $BASE_ENV_FILE"
if [[ -f "$LOCAL_ENV_FILE" ]]; then
  echo "Aplicando overrides locais de $LOCAL_ENV_FILE"
fi

cd "$ROOT_DIR"
exec "$LANGGRAPH_BIN" dev --config "$RUNTIME_CONFIG_FILE" --no-browser "$@"
