"""Generated from .agent.json. Do not edit manually."""

AGENT_DEFAULTS: dict[str, object] = {
    "app_name": "SDR MR Doctors",
    "app_slug": "sdr-mr-doctors",
    "pipefacil_timeout_seconds": 20.0,
    "pipefacil_media_max_bytes": 25000000,
    "pipefacil_webhook_idempotency_ttl_seconds": 86400,
    "pipefacil_ai_attendance_field_slug": "atendimento_por_ia",
    "pipefacil_max_tokens_per_lead": 0,
    "pipefacil_conversation_history_path": "/api/v1/messages",
    "pipefacil_webhook_signature_header": "X-Pipefacil-Signature-256",
    "generated_audio_enabled": False,
    "generated_audio_auto_enabled": False,
    "generated_audio_auto_min_chars": 650,
    "generated_audio_max_chars": 1200,
    "generated_audio_ttl_seconds": 86400,
    "generated_audio_storage_dir": ".runtime/generated-audio",
    "generated_audio_auto_text": "Te mandei um audio para explicar melhor.",
    "generated_audio_convert_to_ogg_opus": False,
    "elevenlabs_base_url": "https://api.elevenlabs.io",
    "elevenlabs_voice_id": "RGymW84CSmfVugnA5tvA",
    "elevenlabs_model_id": "eleven_v3",
    "elevenlabs_output_format": "opus_48000_96",
    "elevenlabs_tts_cost_per_1k_chars_usd": None,
    "elevenlabs_timeout_seconds": 30.0,
    "elevenlabs_max_attempts": 2,
    "elevenlabs_retry_backoff_seconds": 0.5,
    "elevenlabs_voice_stability": 0.45,
    "elevenlabs_voice_similarity_boost": 0.85,
    "elevenlabs_voice_style": 0.35,
    "elevenlabs_voice_use_speaker_boost": True,
    "elevenlabs_voice_speed": 1.0,
    "openai_model": "gpt-5.3-chat-latest",
    "openai_transcription_model": "gpt-4o-mini-transcribe",
    "openai_specialists_enabled": False,
    "openai_specialist_model": None,
    "openai_specialist_max_turns": 8,
    "langfuse_pipefacil_user_id_mode": "contact_id",
}
